const exerciseData = [
	{
		category: 'Squat',
		weaknesses: [
			{
				label: 'Sticking point na dole',
				value: 'squat_bottom',
				types: {
					wariacja: [
						'Paused Low Bar Squat',
						'Paused High Bar Squat',
						'ATG High Bar Squat',
						'Low Pinn Low Bar Squat',
						'Low Pinn High Bar Squat',
						'Anderson bottom Squat',
					],
					akcesoryjne: [
            			'Belt Squat', 
            			'FFE Bulgarian Split Squat', 
            			'Cyclist Split Squat',
						'Dumbbell Bulgarian Split Squat',
						'Barbell Bulgarian Split Squat',
						'Dumbbell Lunges',
						'Barbell Lunges',
						'Reverse Dumbbell Lunges',
						'Reverse Barbell Lunges',
						'Barbell Front Rack Reverse Lunge',
						'Barbell Zercher Reverse Lunges'
          			],
					izolowane: [
						'Sisy Squat',
						'poliquin step up',
						'reverse nordic curl',
						'machine leg extensions',
						'Machine Leg Press',
						'single leg cyclist squat',
						'Single Leg Leg Press',
						'Single Leg Seated machine Leg Extension'
					],
					stablizacyjne: [
            			'Reverse Split squat + rotation',
						'Floating Split Squat',
            			'Hip Drop Box', 
            			'Hip Areoplane', 
            			'Asissted hip Areoplane',
						'Landmine Hip Areoplane',
          			],
				},
			},
			{
				label: 'Sticking point na górze',
				value: 'squat_upper',
				types: {
					wariacja: [
             			'High Pinn Low Bar Squat',
						'High Pinn High Bar Squat',
						'High Pinn High Bar Squat',
             			'Front Squat', 
             			'Zercher Squat',
						'Anderson Squat',
					],
					akcesoryjne: [
						'Belt Squat', 
            			'FFE Bulgarian Split Squat', 
            			'Cyclist Split Squat',
						'Dumbbell Bulgarian Split Squat',
						'Barbell Bulgarian Split Squat',
						'Dumbbell Lunges',
						'Barbell Lunges',
						'Reverse Dumbbell Lunges',
						'Reverse Barbell Lunges',
						'Barbell Front Rack Reverse Lunge',
						'Barbell Zercher Reverse Lunges'
					],
					izolowane: [
						'Sisy Squat',
						'poliquin step up',
						'reverse nordic curl',
						'machine leg extensions',
						'Machine Leg Press',
						'single leg cyclist squat',
						'Single Leg Leg Press',
						'Single Leg Seated machine Leg Extension'
					],
					stablizacyjne: [
            			'Reverse Split squat + rotation',
						'Floating Split Squat', 
            			'Hip Drop Box',
            			'Hip Areoplane', 
            			'Asissted hip Areoplane',
						'Landmine Hip Areoplane',
          			],
				},
			},
			{
				label: 'But Wink',
				value: 'core',
				types: {
					wariacja: [
						'Paused Low Bar Squat',
						'Paused High Bar Squat',
						'Paused ATG High Bar Squat',
						'Paused Low Pinn Low Bar Squat',
						'Paused Low Pinn High Bar Squat',
						'Paused Anderson bottom Squat',
					],
					akcesoryjne: [
						'Belt Squat', 
            			'FFE Bulgarian Split Squat', 
            			'Cyclist Split Squat',
						'Dumbbell Bulgarian Split Squat',
						'Barbell Bulgarian Split Squat',
						'Dumbbell Lunges',
						'Barbell Lunges',
						'Reverse Dumbbell Lunges',
						'Reverse Barbell Lunges',
						'Barbell Front Rack Reverse Lunge',
						'Barbell Zercher Reverse Lunges'
					],
					izolowane: [
						'Sisy Squat',
						'poliquin step up',
						'reverse nordic curl',
						'machine leg extensions',
						'Machine Leg Press',
						'single leg cyclist squat',
						'Single Leg Leg Press',
						'Single Leg Seated machine Leg Extension'
					],
					stablizacyjne: [
            			'Reverse Split squat + rotation',
						'Floating Split Squat', 
            			'Hip Drop Box', 
            			'Hip Areoplane', 
            			'Asissted hip Areoplane',
						'Landmine Hip Areoplane',
          			],
				},
			},
			{
				label: 'Przysiad Dzień dobry',
				value: 'goodmorning',
				types: {
					wariacja: [
						'High Bar Squat',
						'High Bar Box Squat',
						'Front Squat', 
             			'Zercher Squat',
						'Anderson Squat',
						'Hatfield Squat',
					],
					akcesoryjne: [
						'Belt Squat', 
            			'FFE Bulgarian Split Squat', 
            			'Cyclist Split Squat',
						'Dumbbell Bulgarian Split Squat',
						'Barbell Bulgarian Split Squat',
						'Dumbbell Lunges',
						'Barbell Lunges',
						'Reverse Dumbbell Lunges',
						'Reverse Barbell Lunges',
						'Barbell Front Rack Reverse Lunge',
						'Barbell Zercher Reverse Lunges'
					],
					izolowane: [
						'Sisy Squat',
						'poliquin step up',
						'reverse nordic curl',
						'machine leg extensions',
						'Machine Leg Press',
						'single leg cyclist squat',
						'Single Leg Leg Press',
						'Single Leg Seated machine Leg Extension'
					],
					stablizacyjne: [
            			'Reverse Split squat + rotation',
						'Floating Split Squat', 
            			'Hip Drop Box', 
            			'Hip Areoplane', 
            			'Asissted hip Areoplane',
						'Landmine Hip Areoplane',
          			],
				},
			},
			{
				label: 'Hip Shift',
				value: 'hip_shift',
				types: {
					wariacja: [
						'Tempo 3010 Low Bar Squat',
						'Tempo 3010 High Bar Squat',
						'Tempo 3010 ATG High Bar Squat',
						'Tempo 3010 Low Pinn Low Bar Squat',
						'Tempo 3010 Low Pinn High Bar Squat',
						'Tempo 3010 Anderson bottom Squat',
					],
					akcesoryjne: [
						'Belt Squat', 
            			'FFE Bulgarian Split Squat', 
            			'Cyclist Split Squat',
						'Dumbbell Bulgarian Split Squat',
						'Barbell Bulgarian Split Squat',
						'Dumbbell Lunges',
						'Barbell Lunges',
						'Reverse Dumbbell Lunges',
						'Reverse Barbell Lunges',
						'Barbell Front Rack Reverse Lunge',
						'Barbell Zercher Reverse Lunges'
					],
					izolowane: [
						'Sisy Squat',
						'poliquin step up',
						'reverse nordic curl',
						'machine leg extensions',
						'Machine Leg Press',
						'single leg cyclist squat',
						'Single Leg Leg Press',
						'Single Leg Seated machine Leg Extension'
					],
					stablizacyjne: [
            			'Reverse Split squat + rotation',
						'Floating Split Squat', 
            			'Hip Drop Box', 
            			'Hip Areoplane', 
            			'Asissted hip Areoplane',
						'Landmine Hip Areoplane',
          			],
				},
			},
			
		],
		
	},
	{
		category: 'Bench',
		weaknesses: [
			{
				label: 'Poprawne opuszczanie sztangi',
				value: 'correct_lowering',
				types: {
					wariacja: [
						'Tempo 3010 Bench Press',
						'Tempo 3010 Low Pinn Bench Press',
					],
					akcesoryjne: [
						'Tempo 3010 Halfkneeling landmine press', 
						'Tempo 3010 landmine press', 
						'Tempo 3010 Dumbell Bench Press', 
						'Tempo 3010 Incline Dumbell Bench Press', 
						'Tempo 3010 seated dumbbell sholder press',
						'Tempo 3010 Hook Lying Dumbbell Bench Press',
						'Tempo 3010 Military Press',
						'Tempo 3010 Setaed Military Press',
						'Tempo 3010 Seated Smith Military Press'
					],
					izolowane: [
						'Dumbell Around the world',
						'Push up',
						'Cable flys',
						'Dumbbell Flys',
						'Dumbbell incline Flys',
						'Poliquin Flys',
						'Pec Deck',
						'Dumbbell Floor Fly'
					],
					stablizacyjne: [	
						'Halfkneeling kettelbell Press',
						'Tsunami Military Press', 
						'halfkneeling side kb press',
						'Kettelbell Windmill',
						'Lateral Landmine Press',
						'Cable external Rotation',
						'Active Hang',
						'bradford press',
						'side lying kb press',
						'ez-bar reverse grip incline bench press',
						'seated kb bottom up press',
					],
				},
			},
			{
				label: 'Wypchnięcie sztangi z klatki',
				value: 'bench bottom',
				types: {
					wariacja: [
						'3sc Paused Bench Press',
						'4sc Paused Bench Press',
						'3sc Paused Low Pinn Bench Press',
						'Dead Bench Press',
					],
					akcesoryjne: [
						'halfkneeling landmine press', 
						'Paused Incline Dumbell Bench Press',
						'Paused Dumbell Bench Press',
						'Seated dumbbell sholder press', 
						'3sc Paused Hook Lying Dumbbell Bench Press',
						'Dumbbell Bench Press',
						'seated military press',
						'Military Press',
						'Feet up Dumbbell Bench Press',
						'Hammer Chest Press',
						'Hook Lying Dumbbell Bench Press',
						'Decline Dumbbell Bench Press',
						'Seated Smith Military Press',
					],
					izolowane: [
						'Dumbell Around the world',
						
						'Push up',
						'Cable flys',
						'Dumbbell Flys',
						'Dumbbell incline Flys',
						'Poliquin Flys',
						'Pec Deck',
						'Dumbbell Floor Fly'
					],
					stablizacyjne: [	
						'Halfkneeling kettelbell Press',
						'Tsunami Military Press', 
						'halfkneeling side kb press', 
						'Kettelbell Windmill',
						'Lateral Landmine Press',
						'Cable external Rotation',
						'Active Hang',
						'bradford press',
						'side lying kb press',
						'ez-bar reverse grip incline bench press',
						'seated kb bottom up press',
					],
				},
			},
			{
				label: 'Dalszy ruch kilka cm nad klatką',
				value: 'above_bench',
				types: {
					wariacja: [
						'Spoto Bench Press',
						'3sc Paused Spoto Bench Press',
						'Pinn Bench Press',
						'Dead Bench Press',
					],
					akcesoryjne: [
						'halfkneeling landmine press', 
						'Incline Dumbell Bench Press',
						'Seated dumbbell sholder press', 
						'Dumbbell Bench Press',
						'seated military press',
						'Military Press',
						'Feet up Dumbbell Bench Press',
						'Hammer Chest Press',
						'Hook Lying Dumbbell Bench Press',
						'Decline Dumbbell Bench Press',
					],
					izolowane: [
						'Dumbell Around the world', 
						'Push up',
						'Cable flys',
						'Dumbbell Flys',
						'Dumbbell incline Flys',
						'Poliquin Flys',
						'Pec Deck',
						'Dumbbell Floor Fly',
					],
					stablizacyjne: [	
						'Halfkneeling kettelbell Press',
						'halfkneeling side kb press', 
						'Kettelbell Windmill',
						'Lateral Landmine Press',
						'Cable external Rotation', 
						'Active Hang',
						'bradford press',
						'side lying kb press',
						'ez-bar reverse grip incline bench press',
						'seated kb bottom up press',
					],
				},
			},
			{
				label: 'Połowa zakresu ruchu',
				value: 'few_above_bench',
				types: {
					wariacja: [
						'Spoto Bench Press',
						'High Pinn Bench Press', 
						'Dead Bench Press',
						'Florr Bench Press',
						'close grip incline deadstop press'
					],
					akcesoryjne: [
						'Incline Close grip Bench Press',
						'halfkneeling landmine press', 
						'JM Press', 
						'Smith JM Press', 
						'Seated dumbbell sholder press', 
						'Dumbbell Bench Press',
						'seated military press',
						'Military Press',
						'Feet up Dumbbell Bench Press',
						'Hammer Chest Press',
						'Hook Lying Dumbbell Bench Press',
						'Decline Dumbbell Bench Press',
					],
					izolowane: [
						'curl barbell skull crushers',
						'dumbell skull crushers',
						'dead stop skull crusher',
						'tate press', 
						'Push up',
						'Cable Tate Press',
						'Cable flys',
						'Dumbbell Flys',
						'Dumbbell incline Flys',
						'Poliquin Flys',
						'Pec Deck',
						'Dumbbell Floor Fly'
					],
					stablizacyjne: [	
						'Halfkneeling kettelbell Press',
						'halfkneeling side kb press',
						'Kettelbell Windmill',
						'Lateral Landmine Press',
						'Cable external Rotation',
						'Active Hang',
						'bradford press',
						'side lying kb press',
						'ez-bar reverse grip incline bench press',
						'seated kb bottom up press',
					],
				},
			},
			{
				label: 'Końcówka zakresu ruchu(lockout)',
				value: 'lockout_bench',
				types: {
					wariacja: [
						'Close Grip Bench Press', 
						'Close Grip Pinn Bench Press', 
						'Florr Bench Press',
						'close grip incline deadstop press',
					],
					akcesoryjne: [
						'Incline Close grip Bench Press',
						'halfkneeling landmine press', 
						'Seated dumbbell Sholder press',
						'Dumbbell Bench Press',
						'seated military press',
						'Military Press',
						'Feet up Dumbbell Bench Press',
						'Hammer Chest Press',
						'Hook Lying Dumbbell Bench Press',
						'Decline Dumbbell Bench Press',
					],
					izolowane: [
						'skull crushers',
						'dumbell skull crushers',
						'dead stop skull crusher',
						'JM Press', 
						'Smith JM Press',
						'tate press', 
						'Push up',
						'Cable Tate Press',
						'Cable flys',
						'Dumbbell Flys',
						'Dumbbell incline Flys',
						'Poliquin Flys',
						'Pec Deck',
						'Dumbbell Floor Fly',
					],
					stablizacyjne: [
						'Halfkneeling kettelbell Press',
						'halfkneeling side kb press',
						'Kettelbell Windmill',
						'Lateral Landmine Press',
						'Cable external Rotation',
						'Active Hang',
						'bradford press',
						'side lying kb press',
						'ez-bar reverse grip incline bench press',
						'seated kb bottom up press',	
					],
					},
				},
				{
					label: 'Utrzymanie Techniki na dużym ciężarze',
					value: 'maintaining_bench',
					types: {
						wariacja: [
							'Tempo 3010 Bench Press',
							'Tempo 3010 Low Pinn Bench Press',
						],
						akcesoryjne: [
							'halfkneeling landmine press', 
							'Incline Dumbell Bench Press',
							'Seated dumbbell sholder press', 
							'Dumbbell Bench Press',
							'seated military press',
							'Military Press',
							'Feet up Dumbbell Bench Press',
							'Hammer Chest Press',
							'Hook Lying Dumbbell Bench Press',
							'Decline Dumbbell Bench Press',
							
						],
						izolowane: [
							'Dumbell Around the world', 
							'Push up',
							'Cable flys',
							'Dumbbell Flys',
							'Dumbbell incline Flys',
							'Poliquin Flys',
							'Pec Deck',
							'Dumbbell Floor Fly'
						],
						stablizacyjne: [
							'Halfkneeling kettelbell Press',
							'halfkneeling side kb press',
							'Kettelbell Windmill',
							'Lateral Landmine Press', 
							'Cable external Rotation',
							'Active Hang',
							'bradford press',
							'side lying kb press',
							'ez-bar reverse grip incline bench press',
							'seated kb bottom up press',
					],
				},
			},
		],
	},
	{
		category: 'Deadlift',
		weaknesses: [
			{
				label: 'Oderwanie sztangi(ciąg sumo)',
				value: 'deadlift_start_sumo',

				types: {
					wariacja: [
						'Hover Sumo Deadlift', 
						'Snatch grip Deadlift',
						'Deficit Sumo Deadlift',
						'Box Sumo Deadlift'
					],
					akcesoryjne: [
						'GHR',
						'Glute Bridge', 
						'Superman Landing', 
						'Dumbbell Cossack squat',
						'Kettelbell Cossack squat',
						'Hip Thrust',
						'Dumbbell Split Stance RDL',
						'Barbell Split Stance RDL',
						'Trap Bar Split Stance RDL',
						'Power Shrugs',
					],
					izolowane: [
						'Swiss Ball Leg Curl',
						'Machine Leg Leg Curl',
						'Single Leg Leg Press', 
						'Single leg seated machine leg curl', 
						'Goblet Cossack Squat',
						'Barbell Cossack Squat',
						'Dumbbell Cossack Squat',
						'Dumbbell RDL',
						'Single Leg Lying machine leg curl',
						'Split Stance Trap bar Deadlift',
						'ez bar hamstring curl',
					],
					stablizacyjne: [
						'Dumbbell Single leg RDL', 
						'Barbell Single leg RDL',
						'Single leg barbell RDL',
						  
						'Hip Drop Box', 
						'One Leg Hip Thrust', 
						'One Leg Glute Bridge',
						'Glute Crusher',
						'Zercher Glute Crusher',
					],
				},
			},
			{
				label: 'Oderwanie sztangi(ciąg klasyczny)',
				value: 'deadlift_start_classic',

				types: {
					wariacja: [
						'Hover Classic Deadlift', 
						'Snatch grip Deadlift',
						'Deficit Classic Deadlift',
						'Box Deadlift'
					],
					akcesoryjne: [
						'GHR',
						'Glute Bridge', 
						'Superman Landing', 
						'Hip Thrust', 
						'Back Extension with plate',
						'Back Extension with barbell',
						'Power Shrugs',
					],
					izolowane: [
						'Swiss Ball Leg Curl',
						'Machine Leg Leg Curl',
						'Single Leg Leg Press',
						'Single leg seated machine leg curl', 
						'Dumbbell RDL', 
						'Single Leg Lying machine leg curl',
						'Split Stance Trap bar Deadlift',
						'ez bar hamstring curl',
					],
					stablizacyjne: [
						'Dumbbell Single leg RDL', 
						'Barbell Single leg RDL',
						'Single leg barbell RDL',
						  
						'Hip Drop Box', 
						'One Leg Hip Thrust', 
						'One Leg Glute Bridge',
					],
				},
			},
			{
				label: 'Lockout(ciąg sumo)',
				value: 'lockout_sumo',
				types: {
					wariacja: [
						'Snatch grip RDL', 
						'Sumo block pull',
						'Paused Sumo Deadlift above the knee'
					],
					akcesoryjne: [
						'GHR',
						'Glute Bridge', 
						'Dumbbell Cossack squat',
						'Kettelbell Cossack squat',
						'Hip Thrust',
						'Power Shrugs',
					],
					izolowane: [
						'Swiss Ball Leg Curl',
						'Machine Leg Leg Curl', 
						'Single leg seated machine leg curl', 
						'Goblet Cossack Squat',
						'Barbell Cossack Squat',
						'Dumbbell Cossack Squat',
						'Dumbbell RDL',
						'Split Stance Trap bar Deadlift',
						'ez bar hamstring curl',
					],
					stablizacyjne: [
						'Dumbbell Single leg RDL', 
						'Barbell Single leg RDL',
						'Single leg barbell RDL',
						  
						'Hip Drop Box', 
						'One Leg Hip Thrust', 
						'One Leg Glute Bridge',
					],
				},
			},
			{
				label: 'Lockout(ciąg klasyczny)',
				value: 'lockout_classic',
				types: {
					wariacja: [
						'Block pull', 
						'Snatch grip RDL',
						'Paused Deadlift above the knee'
					],
					akcesoryjne: [
						'GHR',
						'Glute Bridge', 
						'Hip Thrust', 
						'Back Extension with plate',
						'Back Extension with barbell',
						'Power Shrugs',
					],
					izolowane: [
						'Swiss Ball Leg Curl',
						'Machine Leg Leg Curl', 
						'Single leg seated machine leg curl', 
						'Dumbbell RDL',
						'Single Leg Lying machine leg curl',
						'Split Stance Trap bar Deadlift',
						'ez bar hamstring curl',
					],
					stablizacyjne: [
						'Dumbbell Single leg RDL', 
						'Barbell Single leg RDL',
						'Single leg barbell RDL',
						  
						'Hip Drop Box', 
						'One Leg Hip Thrust', 
						'One Leg Glute Bridge',
					],
				},
			},
			{
				label: 'Pod kolanem(ciąg sumo)',
				value: 'below_the_knee_sumo',
				types: {
					wariacja: [
						'Deadlfit sumo to the knee',
						'Paused Sumo Deadlift below the knee'
					],
					akcesoryjne: [
						'GHR',
						'Glute Bridge', 
						'Dumbbell Cossack squat',
						'Kettelbell Cossack squat',
						'Hip Thrust',
						'Power Shrugs',
					],
					izolowane: [
						'Swiss Ball Leg Curl',
						'Machine Leg Leg Curl', 
						'Single leg seated machine leg curl', 
						'Goblet Cossack Squat',
						'Barbell Cossack Squat',
						'Dumbbell Cossack Squat',
						'Split Stance Trap bar Deadlift',
						'ez bar hamstring curl', 
					],
					stablizacyjne: [
						'Dumbbell Single leg RDL', 
						'Barbell Single leg RDL',
						'Single leg barbell RDL',
						  
						'Hip Drop Box', 
						'One Leg Hip Thrust', 
						'One Leg Glute Bridge',
					],
				},
			},
			{
				label: 'Pod kolanem(ciąg classic)',
				value: 'below_the_knee_classic',
				types: {
					wariacja: [
						'Deadlfit to the knee',
						'Paused Deadlift below the knee'
					],
					akcesoryjne: [
						'GHR',
						'Glute Bridge', 
						'Hip Thrust', 
						'Back Extension with plate',
						'Back Extension with barbell',
						'Power Shrugs',
					],
					izolowane: [
						'Swiss Ball Leg Curl',
						'Machine Leg Leg Curl', 
						'Single leg seated machine leg curl', 
						'Single Leg Lying machine leg curl',
						'Split Stance Trap bar Deadlift',
						'ez bar hamstring curl',
					],
					stablizacyjne: [
						'Dumbbell Single leg RDL', 
						'Barbell Single leg RDL',
						'Single leg barbell RDL',
						 
						'Hip Drop Box', 
						'One Leg Hip Thrust', 
						'One Leg Glute Bridge',
					],
				},
			},
		],
	},
]

const independentExercises = {
  back: {
    backHorizontal: [
      'Barbell Rows',
      'Underhand grip Barbell Rows',
      'Pendley Rows',
	  'Woolam Row',
	  'Barbell Seal Row',
	  'Dumbell Seal Row',
	  'Incline Bench Dumbbell Seal Row',
      'contralateral dumbell row',
      'single arm dumbell row',
      'chest supported dumbell row',
      'chest supported barbell row',
      'meadows Row',
      'seated calbe row',
      'dumbell pullover',
	  'Kettelbell Gorilla Row',
	  'Rounded Back Dumbbell Rows',
	  'Wide Grip Cable Low Row',
	  'Dumbbell Bent-over Row',
	  'Meadows Row'
    ],
    backVertical: [
      'Pull-Ups',
      'Chin-ups',
      'Wide Grip Lat Pulldown',
      'Neutral grip Lat Pulldown',
      'Underhand grip Lat Pulldown',
      'Pull-up hammer grip',
	  'Eccentric pull up',
	  'Eccentric chin up',
	  'Eccentric pull up hammer grip',
	  'Chest supported Single Arm lat pulldown',
	  'Cobra pulldown',
	  'Scott pull',
	  'bent over lock lat pull',
	  'halfkneeling lock lat pulldown',
	  'chest supported lat pullover',
	  'Single Arm Illac Puldown',
	  'Single Arm Seated Lat pull-in',
    ],
    backIsolation: [
	  'Duffin up right row',
	  'Duffin Pulldown',
      'Chest supported No money',
      'prone Y rise',
      'Facepull rotation',
      'prone T rise',
      'cable reverse fly',
      'head supported row',
      'powell raises',
      'prone snow angels',
	  'Serratus uppercut',
	  'Band Pull Apart',
	  'Resisted Scapular Slide',
	  'Kelso Shrugs',
	  'Cable Rear Delt Fly',
	  'TRX prone y raises',
	  'rounded back row',
	  'Invertered Row',
	  'Hammer Row',
	  'Hammer Pull',
	  '90/90 Row',
    ],
	backMix: [
		'Bird Dog Row',
		'Cable Row/w rotation',
		'Split Stance single arm lat pullover'
	]
  },
  
  core: {
    core: [
		'obligues dead bug',
		'dead bug psoas march',
		'copenhagen adduction',
		'panda roll',
		'Side Plank Clamshell',
		'Knee to the bars',
		'GHD sit up',
		'Halfkneeling wood choppers',
		'Stir The Pot',
		'Band Resiseted deadbug',
		'Band Resiseted Hollowbody',
		'Weighted Plank',
		'Bear Sholder Tap',
		'Allahy',
		'Ab Wheel Rolout',
		'Pall Of Press',
		'Pall of Press w/rotation',
		'Kettlebell overhead farmer walk',
		'Plank w/rotation',
		'chaos kb overhead farmer walk',
		'Farmer Walk',
		'Single Arm Farmer Walk',
		'Hollow Body',
		'Trx plank Body Saw',
	]
  },

  sholders: {
	sholders: [
		'Single Arm Cable Lateral Raises',
		'Poliquin Lateral Raises',
		'Single Arm Cable Lateral Raises',
	]
  },

  glutes: {
	glutesGlobal: [
		'Hip Thrust',
		'Glute Bridge',
		'Snatch Grip RDL',
		'RDL',
		'Dumbbell RDL',
	],
	glutesIsolation: [
		'Glute Crushers',
		'Donkey Kick',
		'Frog Pump'
	]
  },
  foreArms: {
	biceps: [
		'Incline dumbbell Biceps Curl',
		'Bayesian Cable Curl',
		'One Arm Bayesian Cable Curl',
		'Barbell Curl',
		'hammer curl',
		'superman curl',
		'barbell curl',
		'Ez bar Biceps Curl (narrow)',
		'Ez Bar Reverse Curl',
		'Incline Bench Preacher Curl',
		'Preacher Machine Curl',
	],
	triceps: [
		'Cable Tate Press',
		'Cable Triceps Extension',
		'JM Press',
		'Smith JM Press',
		'ez bar french press',
		'ez bar skull crusher',
		'rolling back triceps extension',
		'Single Arm Cross Body triceps extension',
		'Cross Body triceps extension',
		'Side Lying Dumbbell triceps Extension',
		'Single Arm Triceps Pushdown',
		'Bayesian Curl',
		'Barbell Skull Crusher',
		'California Press',
		'cable triceps overhead extensions',
		'TRX Triceps Extension',
	]
  }
}


export default exerciseData
export {independentExercises}
